language: python

sudo: false

addons:
  apt:
    packages:
      - liblzma-dev

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

install:
  - pip install -U tox-travis
  - pip install -U pip setuptools setuptools_scm wheel
  - pip install -U nose -rrequirements.txt
  - python setup.py build_ext --inplace

script:
  - tox
