language: python

branches:
  only:
    - master

sudo: false

addons:
  apt:
    packages:
      - liblzma-dev

matrix:
  include:
    - os: linux
      python: 2.7
    - os: linux
      python: 3.5
    - os: linux
      python: 3.6
    - os: osx
      python: 3.6
    - os: linux
      python: 3.7
      dist: xenial
      sudo: true

install:
  - pip install -U tox-travis coveralls pip setuptools wheel
  - python setup.py build_ext --inplace

script:
  - tox

after_success:
  - coveralls
